allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
minimumReleaseAge: 4320
minimumReleaseAgeExclude: []

onlyBuiltDependencies:
  - esbuild
  - sharp
  - '@parcel/watcher'
